apiVersion: v1
kind: Pod
metadata:
  name: nginx-safe
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx:latest
    securityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false