apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-safe
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-safe
  template:
    metadata:
      labels:
        app: nginx-safe
    spec:
      containers:
      - name: nginx
        image: nginxinc/nginx-unprivileged:latest
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          privileged: false