apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: csec5615-apps
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
  timeout: 2m
  wait: true
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: nginx-secure
    namespace: default
  - apiVersion: apps/v1
    kind: Deployment
    name: security-monitor
    namespace: default