---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-app
  namespace: default
spec:
  interval: 10m0s
  path: ./clusters/myAKSCluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: csec
  targetNamespace: default
